#!/bin/bash
set -e
source ./.env
# Output JSON result with all internal variables set
PROMPT_SCHEMA_STRING=`cat ./schemas/prompt/prompt_schema_string.avsc`
CONFLUENT_CLOUD_API_KEY="$CONFLUENT_CLOUD_API_KEY"
CONFLUENT_CLOUD_API_SECRET="$CONFLUENT_CLOUD_API_SECRET"
CC_ENV_ID="$CC_ENV_ID"
CC_SR_ID="$CC_SR_ID"
CC_CLUSTER_ID="$CC_CLUSTER_ID"
PROJECT_ID="$PROJECT_ID"
INDEX_NAME="$INDEX_NAME"
REGION="$REGION"
INDEX_ENDPOINT="$INDEX_ENDPOINT"
DEPLOYED_INDEX_ID="$DEPLOYED_INDEX_ID"
KAGGLE_USERNAME="$KAGGLE_USERNAME"
KAGGLE_KEY="$KAGGLE_KEY"
PROJECT_NUMBER="$PROJECT_NUMBER"
CONTEXT_DATA_SIZE="$CONTEXT_DATA_SIZE"
printf '{
    "CONFLUENT_CLOUD_API_KEY": "%s",
    "CONFLUENT_CLOUD_API_SECRET": "%s",
    "PROMPT_SCHEMA_STRING": "%s",
    "CC_ENV_ID":"%s",
    "CC_SR_ID":"%s",
    "CC_CLUSTER_ID":"%s",
    "PROJECT_ID":"%s",
    "INDEX_NAME":"%s",
    "REGION":"%s",
    "INDEX_ENDPOINT":"%s",
    "DEPLOYED_INDEX_ID":"%s",
    "KAGGLE_USERNAME":"%s",
    "KAGGLE_KEY":"%s",
    "PROJECT_NUMBER":"%s",
    "CONTEXT_DATA_SIZE":"%s"
}' "$CONFLUENT_CLOUD_API_KEY" "$CONFLUENT_CLOUD_API_SECRET" "$PROMPT_SCHEMA_STRING" "$CC_ENV_ID" "$CC_SR_ID" "$CC_CLUSTER_ID" "$PROJECT_ID" "$INDEX_NAME" "$REGION" "$INDEX_ENDPOINT" "$DEPLOYED_INDEX_ID" "$KAGGLE_USERNAME" "$KAGGLE_KEY" "$PROJECT_NUMBER" "$CONTEXT_DATA_SIZE"

